<?php
declare(strict_types=1);
final class EmailTemplates{
    private const NAVY='#0B315B'; private const TEAL='#1696A7'; private const BG='#F4F7FA'; private const TEXT='#193247'; private const MUTED='#6A7C8E'; private const BORDER='#DCE5EC';
    private static function shell(string $eyebrow,string $title,string $content,string $badge='NOTIFICACIÓN'): string{
        $company=e(setting('company_name','Tu empresa'));$app=e(setting('app_name','Evaluación Corporativa'));$support=e(setting('support_email',''));$logo=setting('logo_path','');$logoUrl=$logo!==''?app_url($logo):'';$year=date('Y');
        $logoHtml=$logoUrl!==''?'<img src="'.e($logoUrl).'" alt="'.$company.'" style="display:block;max-width:160px;max-height:52px;width:auto;height:auto;border:0">':'<div style="width:46px;height:46px;line-height:46px;text-align:center;border-radius:13px;background:'.self::NAVY.';color:#fff;font-weight:900">EC</div>';
        return '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:640px){.w{width:100%!important}.p{padding-left:22px!important;padding-right:22px!important}.t{font-size:27px!important}}</style></head><body style="margin:0;background:'.self::BG.';font-family:Arial,Helvetica,sans-serif;color:'.self::TEXT.'"><table role="presentation" width="100%"><tr><td align="center" style="padding:34px 14px"><table role="presentation" class="w" width="680" style="width:680px;max-width:680px;background:#fff;border:1px solid '.self::BORDER.';border-radius:18px;border-collapse:separate;overflow:hidden"><tr><td class="p" style="padding:26px 32px;border-top:4px solid '.self::TEAL.';border-bottom:1px solid '.self::BORDER.'"><table role="presentation" width="100%"><tr><td>'.$logoHtml.'</td><td align="right"><strong style="color:'.self::NAVY.'">'.$company.'</strong><div style="font-size:12px;color:'.self::MUTED.';margin-top:4px">'.$app.'</div></td></tr></table></td></tr><tr><td class="p" style="padding:34px 32px 10px"><div style="font-size:11px;font-weight:900;letter-spacing:1.4px;color:'.self::TEAL.';text-transform:uppercase">'.e($eyebrow).'</div><h1 class="t" style="margin:10px 0 0;font-size:32px;line-height:1.18;color:'.self::NAVY.'">'.e($title).'</h1><div style="margin-top:10px"><span style="display:inline-block;padding:7px 12px;border-radius:999px;background:#EAF7F7;color:#0D6C78;font-size:10px;font-weight:900">'.e($badge).'</span></div></td></tr><tr><td class="p" style="padding:14px 32px 36px;font-size:15px;line-height:1.7">'.$content.'</td></tr><tr><td class="p" style="padding:22px 32px;background:#F9FBFC;border-top:1px solid '.self::BORDER.'"><div style="font-size:12px;line-height:1.7;color:'.self::MUTED.'"><strong style="color:'.self::NAVY.'">'.$company.'</strong>'.($support!==''?'<div>Soporte: '.$support.'</div>':'').'<div style="margin-top:8px">© '.$year.' · Mensaje automático.</div></div></td></tr></table></td></tr></table></body></html>';
    }
    public static function test(string $method): string{return self::shell('CONFIGURACIÓN DE CORREO','Prueba enviada correctamente','<p style="margin:0">La conexión <strong>'.e($method).'</strong> está funcionando correctamente.</p><div style="margin-top:20px;padding:16px 18px;background:#EAF7F7;border:1px solid #CEEDEE;border-left:4px solid '.self::TEAL.';border-radius:12px"><strong>Conexión verificada</strong><div style="margin-top:5px;color:'.self::MUTED.'">El sistema ya puede enviar notificaciones.</div></div>','VERIFICADO');}
    public static function submission(array $evaluation): string{$name=e($evaluation['employee_name_snapshot']??'Empleado');$badge=e($evaluation['badge_snapshot']??'');$score=e($evaluation['score']??'0');return self::shell('EVALUACIÓN COMPLETADA','Nueva participación registrada','<p style="margin:0">Se registró correctamente una participación.</p><table role="presentation" width="100%" style="margin-top:20px;background:#F7F9FB;border:1px solid '.self::BORDER.';border-radius:12px"><tr><td style="padding:16px"><strong>'.$name.'</strong><div style="color:'.self::MUTED.';margin-top:4px">Gafete: '.$badge.' · Resultado: '.$score.'/100</div></td></tr></table>','RESULTADO');}
    public static function accountCreated(string $name): string{return self::shell('SEGURIDAD','Cuenta administrativa creada','<p style="margin:0">Hola <strong>'.e($name).'</strong>. Tu cuenta administrativa fue creada correctamente.</p>','CUENTA');}

    public static function passwordReset(string $name,string $url): string{
        $safeName=e($name);$safeUrl=e($url);
        $content='<p style="margin:0">Hola <strong>'.$safeName.'</strong>. Recibimos una solicitud para restablecer tu contraseña administrativa.</p>'
            .'<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin-top:24px"><tr><td bgcolor="'.self::NAVY.'" style="border-radius:11px"><a href="'.$safeUrl.'" target="_blank" style="display:inline-block;padding:13px 20px;font-family:Arial,Helvetica,sans-serif;font-size:14px;font-weight:800;color:#ffffff;text-decoration:none;border-radius:11px">Restablecer contraseña</a></td></tr></table>'
            .'<div style="margin-top:20px;padding:15px 17px;background:#F7F9FB;border:1px solid '.self::BORDER.';border-radius:12px;color:'.self::MUTED.';font-size:13px">Este enlace vence en 30 minutos y solo puede utilizarse una vez. Si no solicitaste el cambio, puedes ignorar este correo.</div>';
        return self::shell('SEGURIDAD','Restablece tu contraseña',$content,'RECUPERACIÓN');
    }
    public static function passwordChanged(string $name): string{
        return self::shell('SEGURIDAD','Contraseña actualizada','<p style="margin:0">Hola <strong>'.e($name).'</strong>. Tu contraseña administrativa se actualizó correctamente.</p><div style="margin-top:20px;padding:15px 17px;background:#EAF7F7;border:1px solid #CEEDEE;border-left:4px solid '.self::TEAL.';border-radius:12px"><strong>Cambio confirmado</strong><div style="margin-top:5px;color:'.self::MUTED.';font-size:13px">Si no realizaste este cambio, contacta al administrador del sistema.</div></div>','SEGURIDAD');
    }
}

