<?php
declare(strict_types=1);
final class EmailService{
    public function config(): ?array{$q=db()->query('SELECT * FROM email_config WHERE active=1 ORDER BY id DESC LIMIT 1');return $q->fetch()?:null;}
    public function validate(array $c): array{$e=[];$m=strtoupper((string)($c['method']??'SMTP'));if($m==='GRAPH'){if(trim((string)($c['graph_tenant_id']??''))==='')$e[]='Tenant ID requerido.';if(trim((string)($c['graph_client_id']??''))==='')$e[]='Client ID requerido.';if(secret_decrypt($c['graph_client_secret']??'')==='')$e[]='Client Secret requerido.';if(!filter_var($c['graph_user']??'',FILTER_VALIDATE_EMAIL))$e[]='Graph User inválido.';}else{if(trim((string)($c['smtp_host']??''))==='')$e[]='Servidor SMTP requerido.';if((int)($c['smtp_port']??0)<1)$e[]='Puerto SMTP inválido.';if(!in_array(strtolower((string)($c['smtp_secure']??'')),['tls','ssl'],true))$e[]='Seguridad SMTP inválida.';if(!filter_var($c['smtp_user']??'',FILTER_VALIDATE_EMAIL))$e[]='Usuario SMTP inválido.';if(secret_decrypt($c['smtp_password']??'')==='')$e[]='Contraseña SMTP requerida.';}return $e;}
    public function test(string $to): array{$c=$this->config();if(!$c)return ['success'=>false,'message'=>'No existe configuración activa.'];return $this->send($to,'Prueba de correo · '.setting('app_name','Evaluación Corporativa'),EmailTemplates::test((string)$c['method']));}
    public function send(string $to,string $subject,string $html,array $options=[]): array{
        if(!filter_var($to,FILTER_VALIDATE_EMAIL))return ['success'=>false,'message'=>'Destino inválido.'];$c=$this->config();if(!$c)return ['success'=>false,'message'=>'Correo no configurado.'];$err=$this->validate($c);if($err)return ['success'=>false,'message'=>implode(' ',$err)];
        $res=strtoupper((string)$c['method'])==='GRAPH'?$this->graph($c,$to,$subject,$html,$options):$this->smtp($c,$to,$subject,$html,$options);
        try{db()->prepare('INSERT INTO mail_log(recipient,subject,method,status,error_message) VALUES(?,?,?,?,?)')->execute([$to,$subject,$c['method'],$res['success']?'sent':'failed',$res['success']?null:$res['message']]);}catch(Throwable){}
        return $res;
    }
    private function emails(string|array|null $v): array{$a=is_array($v)?$v:(preg_split('/[;,\s]+/',trim((string)$v),-1,PREG_SPLIT_NO_EMPTY)?:[]);return array_values(array_unique(array_filter(array_map('trim',$a),fn($x)=>filter_var($x,FILTER_VALIDATE_EMAIL))));}
    private function graph(array $c,string $to,string $subject,string $html,array $options): array{
        if(!function_exists('curl_init'))return ['success'=>false,'message'=>'cURL no está habilitado.'];$tenant=trim((string)$c['graph_tenant_id']);$client=trim((string)$c['graph_client_id']);$secret=secret_decrypt($c['graph_client_secret']);$from=trim((string)$c['graph_user']);
        $ch=curl_init('https://login.microsoftonline.com/'.rawurlencode($tenant).'/oauth2/v2.0/token');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>30,CURLOPT_POSTFIELDS=>http_build_query(['client_id'=>$client,'scope'=>'https://graph.microsoft.com/.default','client_secret'=>$secret,'grant_type'=>'client_credentials']),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);$j=json_decode((string)$raw,true);if($code<200||$code>=300||empty($j['access_token']))return ['success'=>false,'message'=>'Error de token Graph: '.($err?:'HTTP '.$code)];
        $message=['subject'=>$subject,'body'=>['contentType'=>'HTML','content'=>$html],'toRecipients'=>[['emailAddress'=>['address'=>$to]]]];$bcc=array_merge($this->emails($c['bcc']??''),$this->emails($options['bcc']??[]));if($bcc)$message['bccRecipients']=array_map(fn($x)=>['emailAddress'=>['address'=>$x]],array_values(array_unique($bcc)));$reply=trim((string)($c['reply_to']??''));if(filter_var($reply,FILTER_VALIDATE_EMAIL))$message['replyTo']=[['emailAddress'=>['address'=>$reply]]];
        $payload=['message'=>$message,'saveToSentItems'=>(int)($c['save_to_sent_items']??1)===1];$ch=curl_init('https://graph.microsoft.com/v1.0/users/'.rawurlencode($from).'/sendMail');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>45,CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE),CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$j['access_token'],'Content-Type: application/json']]);$resp=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);return $code===202?['success'=>true,'message'=>'Correo enviado con Microsoft Graph.']:['success'=>false,'message'=>'Error Graph: '.($err?:'HTTP '.$code.' '.$resp)];
    }
    private function smtp(array $c,string $to,string $subject,string $html,array $options): array{
        $host=trim((string)$c['smtp_host']);$port=(int)$c['smtp_port'];$secure=strtolower((string)$c['smtp_secure']);$user=trim((string)$c['smtp_user']);$pass=secret_decrypt($c['smtp_password']);$target=($secure==='ssl'?'ssl://':'tcp://').$host.':'.$port;$fp=@stream_socket_client($target,$errno,$errstr,15,STREAM_CLIENT_CONNECT);if(!$fp)return ['success'=>false,'message'=>'Conexión SMTP falló: '.$errstr];stream_set_timeout($fp,20);
        try{$this->expect($fp,[220]);$this->cmd($fp,'EHLO '.($_SERVER['HTTP_HOST']??'localhost'),[250]);if($secure==='tls'){$this->cmd($fp,'STARTTLS',[220]);if(!stream_socket_enable_crypto($fp,true,STREAM_CRYPTO_METHOD_TLS_CLIENT))throw new RuntimeException('No se pudo habilitar TLS.');$this->cmd($fp,'EHLO '.($_SERVER['HTTP_HOST']??'localhost'),[250]);}$this->cmd($fp,'AUTH LOGIN',[334]);$this->cmd($fp,base64_encode($user),[334]);$this->cmd($fp,base64_encode($pass),[235]);$this->cmd($fp,'MAIL FROM:<'.$user.'>',[250]);$recipients=[$to,...$this->emails($c['bcc']??''),...$this->emails($options['bcc']??[])];foreach(array_unique($recipients) as $r)$this->cmd($fp,'RCPT TO:<'.$r.'>',[250,251]);$this->cmd($fp,'DATA',[354]);$fromName=trim((string)($c['from_name']??setting('company_name','Tu empresa')));$headers=['From: '.$this->header($fromName).' <'.$user.'>','To: <'.$to.'>','Subject: =?UTF-8?B?'.base64_encode($subject).'?=','MIME-Version: 1.0','Content-Type: text/html; charset=UTF-8','Content-Transfer-Encoding: base64'];$reply=trim((string)($c['reply_to']??''));if(filter_var($reply,FILTER_VALIDATE_EMAIL))$headers[]='Reply-To: <'.$reply.'>';fwrite($fp,implode("\r\n",$headers)."\r\n\r\n".chunk_split(base64_encode($html))."\r\n.\r\n");$this->expect($fp,[250]);$this->cmd($fp,'QUIT',[221]);fclose($fp);return ['success'=>true,'message'=>'Correo enviado con SMTP.'];}catch(Throwable $e){@fwrite($fp,"QUIT\r\n");@fclose($fp);return ['success'=>false,'message'=>$e->getMessage()];}
    }
    private function header(string $v): string{return preg_match('/[^\x20-\x7E]/',$v)?'=?UTF-8?B?'.base64_encode($v).'?=':str_replace(["\r","\n"],'',$v);}private function cmd($fp,string $c,array $codes):void{fwrite($fp,$c."\r\n");$this->expect($fp,$codes);}private function expect($fp,array $codes):void{$resp='';while(($l=fgets($fp,515))!==false){$resp.=$l;if(strlen($l)<4||$l[3]!=='-')break;}$code=(int)substr($resp,0,3);if(!in_array($code,$codes,true))throw new RuntimeException('SMTP '.$code.': '.trim($resp));}
}
