<?php
declare(strict_types=1);
final class ReportService{
    public function rows(): array{return db()->query("SELECT e.id,e.badge_snapshot AS badge,e.employee_name_snapshot AS name,e.correct_answers,e.total_questions,e.accuracy_score,e.speed_score,e.score,e.response_seconds,e.completed_at,emp.department FROM evaluations e JOIN employees emp ON emp.id=e.employee_id WHERE e.status='completed' ORDER BY e.completed_at DESC")->fetchAll();}
    public function outputXlsx(): never{
        if(!class_exists('ZipArchive'))$this->outputExcelFallback();$rows=$this->rows();$tmp=tempnam(sys_get_temp_dir(),'evalxlsx_');$zip=new ZipArchive();$zip->open($tmp,ZipArchive::CREATE|ZipArchive::OVERWRITE);
        $headers=['Gafete','Nombre','Departamento','Correctas','Preguntas','Exactitud','Rapidez','Puntuación final','Tiempo (s)','Fecha'];$all=[$headers];foreach($rows as $r)$all[]=[(string)$r['badge'],(string)$r['name'],(string)($r['department']??''),(string)$r['correct_answers'],(string)$r['total_questions'],number_format((float)($r['accuracy_score']??$r['score']),1,'.',''),number_format((float)($r['speed_score']??0),1,'.',''),number_format((float)$r['score'],1,'.',''),number_format((float)($r['response_seconds']??0),1,'.',''),(string)$r['completed_at']];
        $sheet='';foreach($all as $ri=>$row){$cells='';foreach($row as $ci=>$val){$ref=$this->col($ci+1).($ri+1);$style=$ri===0?' s="1"':'';$cells.='<c r="'.$ref.'" t="inlineStr"'.$style.'><is><t>'.htmlspecialchars($val,ENT_XML1|ENT_QUOTES,'UTF-8').'</t></is></c>';}$sheet.='<row r="'.($ri+1).'">'.$cells.'</row>';}
        $zip->addFromString('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>');
        $zip->addFromString('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
        $zip->addFromString('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Resultados" sheetId="1" r:id="rId1"/></sheets></workbook>');
        $zip->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
        $zip->addFromString('xl/styles.xml','<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs></styleSheet>');
        $zip->addFromString('xl/worksheets/sheet1.xml','<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols><col min="1" max="1" width="16" customWidth="1"/><col min="2" max="2" width="34" customWidth="1"/><col min="3" max="3" width="24" customWidth="1"/><col min="4" max="10" width="15" customWidth="1"/></cols><sheetData>'.$sheet.'</sheetData><autoFilter ref="A1:J'.max(1,count($all)).'"/></worksheet>');$zip->close();
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="resultados-evaluacion-'.date('Ymd-His').'.xlsx"');header('Content-Length: '.filesize($tmp));readfile($tmp);@unlink($tmp);exit;
    }
    private function outputExcelFallback(): never{
        $rows=$this->rows();
        $filename='resultados-evaluacion-'.date('Ymd-His').'.xls';
        header('Content-Type: application/vnd.ms-excel; charset=UTF-8');
        header('Content-Disposition: attachment; filename="'.$filename.'"');
        echo "\xEF\xBB\xBF";
        echo '<!doctype html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif}table{border-collapse:collapse;width:100%}th{background:#0B315B;color:#fff;font-weight:bold}th,td{border:1px solid #D9E3EC;padding:8px;text-align:left}.score{font-weight:bold}</style></head><body>';
        echo '<h2>'.htmlspecialchars(setting('company_name','Tu empresa'),ENT_QUOTES,'UTF-8').' · '.htmlspecialchars(setting('app_name','Evaluación Corporativa'),ENT_QUOTES,'UTF-8').'</h2>';
        echo '<p>Reporte de resultados · '.date('d/m/Y H:i').'</p><table><thead><tr><th>Gafete</th><th>Nombre</th><th>Departamento</th><th>Correctas</th><th>Preguntas</th><th>Puntuación</th><th>Fecha</th></tr></thead><tbody>';
        foreach($rows as $r){echo '<tr><td>'.htmlspecialchars((string)$r['badge'],ENT_QUOTES,'UTF-8').'</td><td>'.htmlspecialchars((string)$r['name'],ENT_QUOTES,'UTF-8').'</td><td>'.htmlspecialchars((string)($r['department']??''),ENT_QUOTES,'UTF-8').'</td><td>'.(int)$r['correct_answers'].'</td><td>'.(int)$r['total_questions'].'</td><td class="score">'.number_format((float)$r['score'],1).'%</td><td>'.htmlspecialchars((string)$r['completed_at'],ENT_QUOTES,'UTF-8').'</td></tr>';}
        if(!$rows)echo '<tr><td colspan="7">Sin participaciones completadas.</td></tr>';
        echo '</tbody></table></body></html>';exit;
    }
    public function outputPdf(): never{
        $rows=$this->rows();$lines=[];$lines[]=setting('company_name','Tu empresa').' - '.setting('app_name','Evaluacion Corporativa');$lines[]='Reporte de resultados · '.date('d/m/Y H:i');$lines[]='';$lines[]=sprintf('%-12s %-28s %-11s %-8s %-16s','GAFETE','NOMBRE','RESULTADO','NOTA','FECHA');$lines[]=str_repeat('-',80);foreach($rows as $r){$lines[]=sprintf('%-12s %-28s %-11s %-8s %-16s',substr($this->ascii($r['badge']),0,12),substr($this->ascii($r['name']),0,28),$r['correct_answers'].'/'.$r['total_questions'],number_format((float)$r['score'],1),date('d/m/Y H:i',strtotime((string)$r['completed_at'])));}if(!$rows)$lines[]='Sin participaciones completadas.';$pdf=$this->simplePdf($lines);header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="resultados-evaluacion-'.date('Ymd-His').'.pdf"');header('Content-Length: '.strlen($pdf));echo $pdf;exit;
    }
    private function ascii(string $s): string{$x=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$s);return $x===false?$s:$x;}
    private function col(int $n): string{$s='';while($n>0){$n--;$s=chr(65+$n%26).$s;$n=intdiv($n,26);}return $s;}
    private function simplePdf(array $lines): string{$pages=array_chunk($lines,45);$objects=[];$pageIds=[];$fontId=3;$next=4;foreach($pages as $page){$pageId=$next++;$contentId=$next++;$pageIds[]=$pageId;$y=800;$stream="BT /F1 10 Tf 48 800 Td 12 TL\n";foreach($page as $line){$safe=str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$line);$stream.='('.$safe.") Tj T*\n";}$stream.="ET";$objects[$contentId]="<< /Length ".strlen($stream)." >>\nstream\n$stream\nendstream";$objects[$pageId]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 $fontId 0 R >> >> /Contents $contentId 0 R >>";}$kids=implode(' ',array_map(fn($id)=>$id.' 0 R',$pageIds));$objects[1]='<< /Type /Catalog /Pages 2 0 R >>';$objects[2]='<< /Type /Pages /Kids ['.$kids.'] /Count '.count($pageIds).' >>';$objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>';ksort($objects);$pdf="%PDF-1.4\n";$offsets=[0=>0];$max=max(array_keys($objects));for($i=1;$i<=$max;$i++){$offsets[$i]=strlen($pdf);$pdf.=$i." 0 obj\n".($objects[$i]??'<<>>')."\nendobj\n";}$xref=strlen($pdf);$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf('%010d 00000 n ', $offsets[$i])."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";return $pdf;}
}
