<?php
require_once dirname(__DIR__).'/app/bootstrap.php';
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
$pdo=db();$app=setting('app_name','Evaluación Corporativa');$company=setting('company_name','Tu empresa');$logo=setting('logo_path','');$favicon=site_favicon('../');$gameCampaignImage=setting('game_campaign_image','assets/img/soar-cybersecurity-2026.jpg');
if(isset($_GET['change'])){unset($_SESSION['participant_employee_id'],$_SESSION['participant_employee_badge'],$_SESSION['game_employee_id'],$_SESSION['game_employee_badge']);header('Location: ./?participant=changed');exit;}
$player=null;$playerId=(int)($_SESSION['participant_employee_id']??$_SESSION['game_employee_id']??0);
if($playerId>0){$st=$pdo->prepare("SELECT id,badge,name,department FROM employees WHERE id=? AND status='active' LIMIT 1");$st->execute([$playerId]);$player=$st->fetch()?:null;if($player){$_SESSION['participant_employee_id']=(int)$player['id'];$_SESSION['participant_employee_badge']=(string)$player['badge'];}else{unset($_SESSION['participant_employee_id'],$_SESSION['participant_employee_badge'],$_SESSION['game_employee_id'],$_SESSION['game_employee_badge']);}}
$sessionEmp=(int)($_SESSION['participant_employee_id']??$_SESSION['game_employee_id']??0);$gameGroup='';$gameGroupDescription='';if($sessionEmp>0){$gg=$pdo->prepare('SELECT game_group FROM employees WHERE id=?');$gg->execute([$sessionEmp]);$gameGroup=trim((string)($gg->fetchColumn()?:''));if($gameGroup!==''){$gd=$pdo->prepare('SELECT description FROM content_groups WHERE name=? LIMIT 1');$gd->execute([$gameGroup]);$gameGroupDescription=trim((string)($gd->fetchColumn()?:''));}}$gameGroupSql=$gameGroup!==''?' AND group_name='.$pdo->quote($gameGroup):'';$allGames=$pdo->query('SELECT id,title,slug,game_type,category,group_name,difficulty,intro,time_limit_seconds,sound_enabled,content_json,sort_order FROM games WHERE active=1'.$gameGroupSql.' ORDER BY sort_order,id')->fetchAll();if($gameGroup===''&&$allGames){$gameGroup=trim((string)($allGames[0]['group_name']??''));if($gameGroup!==''){$gd=$pdo->prepare('SELECT description FROM content_groups WHERE name=? LIMIT 1');$gd->execute([$gameGroup]);$gameGroupDescription=trim((string)($gd->fetchColumn()?:''));}}$gameExperienceTitle=$gameGroup!==''?$gameGroup:'Juegos interactivos';
$gameOrderMode=setting('game_order_mode','sequential');$gameDisplayMode=setting('game_display_mode','all');$gamesPerPortal=max(1,(int)setting('games_per_portal','6'));$gameNavigationMode=setting('game_navigation_mode','free');$gameCompletionMode=setting('game_completion_mode','all');$gamesRequiredSetting=max(1,(int)setting('games_required_completion','1'));
$rulesSource=$gameDisplayMode.'|'.$gamesPerPortal.'|'.$gameOrderMode.'|'.implode(',',array_map(static fn($g)=>(int)$g['id'].':'.(int)$g['sort_order'],$allGames));$rulesHash=hash('sha256',$rulesSource);$games=$allGames;
if($player){
    $st=$pdo->prepare('SELECT DISTINCT game_id FROM game_attempts WHERE employee_id=? AND completed_at IS NOT NULL ORDER BY game_id');$st->execute([(int)$player['id']]);$completedExistingIds=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));$hasStarted=(bool)$completedExistingIds;
    $st=$pdo->prepare('SELECT ga.rules_hash,g.id,g.title,g.slug,g.game_type,g.category,g.difficulty,g.intro,g.time_limit_seconds,g.sound_enabled,g.content_json,g.sort_order FROM game_assignments ga JOIN games g ON g.id=ga.game_id AND g.active=1 WHERE ga.employee_id=? ORDER BY ga.position,ga.id');$st->execute([(int)$player['id']]);$assignedRows=$st->fetchAll();$assignmentHash=$assignedRows?(string)$assignedRows[0]['rules_hash']:'';
    $mustAssign=!$assignedRows||(!$hasStarted&&$assignmentHash!==$rulesHash);
    if($mustAssign&&$allGames){
        $completedPool=$hasStarted?array_values(array_filter($allGames,static fn($g)=>in_array((int)$g['id'],$completedExistingIds,true))):[];$remaining=array_values(array_filter($allGames,static fn($g)=>!in_array((int)$g['id'],$completedExistingIds,true)));if($gameOrderMode==='random'&&count($remaining)>1)shuffle($remaining);$target=$gameDisplayMode==='limited'?min($gamesPerPortal,count($allGames)):count($allGames);$pool=array_merge($completedPool,array_slice($remaining,0,max(0,$target-count($completedPool))));
        try{$pdo->beginTransaction();$pdo->prepare('DELETE FROM game_assignments WHERE employee_id=?')->execute([(int)$player['id']]);$ins=$pdo->prepare('INSERT INTO game_assignments(employee_id,game_id,position,rules_hash) VALUES(?,?,?,?)');foreach($pool as $i=>$g)$ins->execute([(int)$player['id'],(int)$g['id'],$i+1,$rulesHash]);$pdo->commit();$games=$pool;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$games=$pool;}
    }elseif($assignedRows){foreach($assignedRows as &$row)unset($row['rules_hash']);unset($row);$games=$assignedRows;}
    else{$games=[];}
}
$allowedIds=array_map(static fn($g)=>(int)$g['id'],$games);$completedByGame=[];$completedCount=0;$bestAvg=0.0;
if($player){$st=$pdo->prepare('SELECT game_id,COUNT(*) attempts,MAX(score) best_score,MAX(completed_at) last_completed FROM game_attempts WHERE employee_id=? AND completed_at IS NOT NULL GROUP BY game_id');$st->execute([(int)$player['id']]);foreach($st->fetchAll() as $r){$completedByGame[(int)$r['game_id']]=$r;}$completedCount=count(array_intersect(array_keys($completedByGame),$allowedIds));$scores=[];foreach($allowedIds as $id)if(isset($completedByGame[$id]))$scores[]=(float)$completedByGame[$id]['best_score'];$bestAvg=$scores?array_sum($scores)/count($scores):0;}
$goalCount=count($games);$goalReached=$goalCount>0&&$completedCount>=$goalCount;$gameTotalCorrect=0;$gameTotalItems=0;$gameTotalSeconds=0.0;$overallScore=0.0;if($player&&$allowedIds){$ph=implode(',',array_fill(0,count($allowedIds),'?'));$st=$pdo->prepare('SELECT COALESCE(SUM(correct_answers),0),COALESCE(SUM(total_items),0),COALESCE(SUM(response_seconds),0),COALESCE(AVG(score),0) FROM game_attempts WHERE employee_id=? AND completed_at IS NOT NULL AND game_id IN ('.$ph.')');$st->execute(array_merge([(int)$player['id']],$allowedIds));[$gameTotalCorrect,$gameTotalItems,$gameTotalSeconds,$overallScore]=$st->fetch(PDO::FETCH_NUM)?:[0,0,0,0];}$nextPendingId=0;foreach($games as $g){if(!isset($completedByGame[(int)$g['id']])){$nextPendingId=(int)$g['id'];break;}}
$gameId=(int)($_GET['game']??0);$game=null;$latestAttempt=null;$reviewMode=false;
if($gameId&&!$player){header('Location: ./');exit;}
if($gameId&&$player){foreach($games as $g){if((int)$g['id']===$gameId){$game=$g;break;}}if(!$game){header('Location: ./');exit;}$game['items']=json_decode((string)$game['content_json'],true)?:[];if(isset($completedByGame[$gameId])){$st=$pdo->prepare('SELECT id,accuracy_score,speed_score,score,correct_answers,total_items,response_seconds,answers_json,completed_at FROM game_attempts WHERE game_id=? AND employee_id=? AND completed_at IS NOT NULL ORDER BY completed_at DESC,id DESC LIMIT 1');$st->execute([$gameId,(int)$player['id']]);$latestAttempt=$st->fetch()?:null;$reviewMode=(bool)$latestAttempt;}}
$firstName=$player?trim(explode(' ',trim((string)$player['name']))[0]??(string)$player['name']):'';
$gameVisuals=['hotspot'=>'email-alert.svg','binary'=>'phishing-check.svg','scenario'=>'mfa-decision.svg','find'=>'login-errors.svg','speed'=>'speed-shield.svg','order'=>'order-incident.svg','match'=>'concept-map.svg','truefalse'=>'truefalse-lock.svg'];
$gameVisual=$game?'../assets/img/games/'.($gameVisuals[$game['game_type']]??'phishing-check.svg'):'';
$displayGameTitle=static function(array $g): string { $seconds=max(0,(int)($g['time_limit_seconds']??0)); return (($g['game_type']??'')==='speed' && $seconds>0) ? 'Reto de '.$seconds.' segundos' : (string)($g['title']??'Juego'); };
$activeGameTitle=$game?$displayGameTitle($game):'';
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#073763"><title><?=e(browser_title())?> · Juegos</title><link rel="icon" href="<?=e($favicon)?>"><link rel="stylesheet" href="../assets/css/games.css?v=27"><link rel="stylesheet" href="../assets/css/notify.css?v=8"><link rel="stylesheet" href="../assets/vendor/sweetalert2/sweetalert2.local.css?v=8"><script>window.GAME_APP={csrf:<?=json_encode(csrf_token())?>,employee:<?=json_encode($player?['id'=>(int)$player['id'],'badge'=>$player['badge'],'name'=>$player['name'],'department'=>$player['department']??'']:null,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,game:<?=json_encode($game?['id'=>(int)$game['id'],'title'=>$activeGameTitle,'type'=>$game['game_type'],'intro'=>$game['intro'],'difficulty'=>$game['difficulty'],'sound'=>(bool)$game['sound_enabled'],'time_limit'=>(int)($game['time_limit_seconds']??0),'visual'=>$gameVisual,'items'=>$game['items']]:null,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,review:<?=json_encode($reviewMode)?>,attempt:<?=json_encode($latestAttempt?['id'=>(int)$latestAttempt['id'],'score'=>(float)$latestAttempt['score'],'accuracy_score'=>(float)($latestAttempt['accuracy_score']??$latestAttempt['score']),'speed_score'=>(float)($latestAttempt['speed_score']??0),'response_seconds'=>(float)($latestAttempt['response_seconds']??0),'correct'=>(int)$latestAttempt['correct_answers'],'total'=>(int)$latestAttempt['total_items'],'completed_at'=>$latestAttempt['completed_at'],'answers'=>json_decode((string)($latestAttempt['answers_json']??''),true)?:[]]:null,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>};</script></head><body class="<?= $game ? 'game-play-body' : (!$player ? 'games-identify-body' : 'games-list-body') ?>">
<header class="games-topbar"><div class="games-nav"><a class="games-brand" href="./"><span class="heds-navbar-logo"><img src="../assets/img/heds-logo-navbar.jpg" alt="HEDS · Honduras Electrical Distribution Systems"></span><span><strong><?=e($app)?></strong><small>Zona interactiva · <?=e($company)?></small></span></a><div class="nav-actions"><div class="site-switch" aria-label="Cambiar entre sitios"><span class="site-switch-label">SITIOS</span><a class="site-link" href="../" title="Ir al sitio de evaluación"><?=ui_icon('external')?><span>Preguntas</span></a><a class="site-link is-current" href="./" aria-current="page" title="Sitio de juegos"><?=ui_icon('cards')?><span>Juegos</span></a></div><button type="button" class="sound-toggle" data-sound-toggle aria-label="Activar o desactivar sonido">🔊 <span>Sonido</span></button><button class="screen-control" type="button" data-fullscreen-toggle aria-label="Pantalla completa" title="Pantalla completa"><?=ui_icon('fullscreen')?><span data-fullscreen-label>Pantalla completa</span></button><a class="admin-link" href="../admin/" target="_blank" rel="noopener noreferrer" aria-label="Administración" title="Administración · abrir en otra pestaña"><?=ui_icon('settings')?><span>Administración</span><b>→</b></a></div></div></header>
<main class="games-shell <?= $game ? 'is-game-play' : (!$player ? 'is-game-identify' : 'is-games-list') ?>">
<?php if(!$player):?>
<section class="game-identify-shell"><div class="identify-visual"><div class="soar-identify-banner" aria-label="SOAR · Security Opportunity Action Recognition"><img src="../<?=e($gameCampaignImage)?>" alt="SOAR · Security Opportunity Action Recognition"></div><p class="hero-kicker">EXPERIENCIA PERSONALIZADA</p><h1>Antes de jugar,<br>¿quién eres?</h1><p>Ingresa tu gafete. Usaremos tu nombre para saludarte, asignarte los juegos según la configuración y registrar tu participación.</p><div class="identify-points"><span>✓ Juegos asignados para ti</span><span>✓ Progreso identificado por gafete</span><span>✓ Experiencia personalizada</span></div></div><div class="identify-card"><span class="eyebrow">IDENTIFICACIÓN</span><h2>Ingresa tu gafete</h2><p>Confirmaremos tu nombre antes de mostrar tus retos.</p><label for="portalGameBadge">Número de gafete</label><div class="badge-row"><input id="portalGameBadge" data-game-badge inputmode="numeric" pattern="[0-9]+" maxlength="40" autocomplete="off" placeholder="Ej. 4500329" autofocus><button type="button" data-game-identify disabled>Continuar →</button></div><div class="game-employee-preview hidden" data-game-employee-preview></div><small data-game-identify-status>Escribe tu gafete; al encontrarlo confirmaremos tus datos y habilitaremos Continuar.</small></div></section>
<?php elseif(!$game):?>
<section class="player-welcome-bar"><div class="player-welcome-main"><span class="player-avatar"><?=e(user_initials((string)$player['name']))?></span><div><span class="eyebrow">TU ZONA DE JUEGOS</span><h2>¡Hola, <?=e($firstName)?>! 👋</h2><p><?=e($player['name'])?> · Gafete <?=e($player['badge'])?><?=!empty($player['department'])?' · '.e($player['department']):''?></p></div></div><div class="player-progress"><span><small>Asignados</small><strong><?=count($games)?></strong></span><span><small>Completados</small><strong><?=$completedCount?></strong></span><span class="<?=$goalReached?'goal-done':''?>"><small>Pendientes</small><strong><?=max(0,count($games)-$completedCount)?><?=$goalReached?' ✓':''?></strong></span><span><small>Resultado</small><strong><?=number_format((float)$overallScore,0)?>%</strong></span><a href="?change=1" data-game-change-participant><?=ui_icon('refresh')?> Cambiar participante</a></div></section>
<section class="games-hero"><div class="games-hero-copy"><div class="portal-context-line"><span class="portal-kind-pill">JUEGOS</span><span class="portal-context-kicker">APRENDE · JUEGA · RECUERDA</span></div><h1><?=e($gameExperienceTitle)?></h1><?php if($gameGroupDescription!==''):?><p class="experience-description"><?=e($gameGroupDescription)?></p><?php endif;?><p><?=e($firstName)?>, estos son tus retos. <?=($gameOrderMode==='random'?'Tu selección aleatoria quedó guardada y no cambiará al recargar.':'Los juegos siguen el orden configurado por el administrador.')?> Cada juego se registra una sola vez.</p><div class="hero-badges"><span>⚡ Retos rápidos</span><span>🎯 Asignados: <?=count($games)?> juego<?=count($games)===1?'':'s'?></span><span>🔒 Asignación estable</span></div></div><div class="games-hero-aside"><div class="games-hero-campaign" aria-label="Programa SOAR de ciberseguridad"><img src="../<?=e($gameCampaignImage)?>" alt="SOAR · Security Opportunity Action Recognition"><span>PROGRAMA SOAR · CIBERSEGURIDAD</span></div><div class="hero-orbit <?=$goalReached?'is-goal-reached':''?>" aria-hidden="true"><span><?=$goalReached?'🏆':'🛡️'?></span><i></i><b><?=count($games)?></b><small><?=$goalReached?'objetivo cumplido':'juegos asignados'?></small></div></div></section>
<section class="section-head"><div><span class="eyebrow">TUS RETOS</span><h2><?=$goalReached?'¡Completaste todos tus juegos!':'¿Con cuál quieres continuar?'?></h2><p><?=$goalReached?'Tu participación quedó cerrada. Puedes revisar cada juego y su resultado, pero no modificarlo ni repetirlo.':'Todos tus juegos asignados están disponibles. Elige cualquiera; al guardarlo quedará definitivo.'?></p></div><span class="game-count <?=$goalReached?'goal-reached':''?>"><?=$completedCount?> de <?=count($games)?> completados</span></section>
<?php if($completedCount>0):?><section class="portal-result-summary <?=$goalReached?'is-complete':''?>"><div><span class="eyebrow"><?=$goalReached?'PARTICIPACIÓN COMPLETADA':'PROGRESO GUARDADO'?></span><h3><?=$goalReached?'Resultado final de '.e($firstName):'Tu avance hasta ahora'?></h3><p><?=$goalReached?'Ya completaste todos los juegos asignados. Solo puedes revisar tus resultados hasta que un administrador reinicie tus juegos.':'Los juegos completados ya no se pueden repetir ni corregir.'?></p></div><div class="portal-result-metrics"><span><small>Aciertos</small><strong><?=number_format((float)$gameTotalCorrect,0)?> / <?=number_format((float)$gameTotalItems,0)?></strong></span><span><small>Promedio</small><strong><?=number_format((float)$overallScore,1)?>%</strong></span><span><small>Tiempo</small><strong><?=number_format((float)$gameTotalSeconds,1)?> s</strong></span></div></section><?php endif;?>
<section class="games-grid"><?php $icons=['hotspot'=>'🔎','binary'=>'🎣','scenario'=>'🧠','find'=>'🎯','speed'=>'⚡','order'=>'🔢','match'=>'🔗','truefalse'=>'✅'];foreach($games as $i=>$g):$done=$completedByGame[(int)$g['id']]??null;$locked=false;?><?php if($locked):?><article class="game-card is-locked" style="--delay:<?=$i*45?>ms" aria-disabled="true"><?php else:?><a class="game-card <?=$done?'is-completed':''?>" href="?game=<?=$g['id']?>" style="--delay:<?=$i*45?>ms"><?php endif;?><div class="game-card-top"><span class="game-icon"><?=e($icons[$g['game_type']]??'🎮')?></span><span class="difficulty"><?=e($g['difficulty'])?></span></div><div class="game-card-visual"><img src="../assets/img/games/<?=e($gameVisuals[$g['game_type']]??'phishing-check.svg')?>" alt="Ilustración de <?=e($g['title'])?>"></div><span class="game-category"><?=e($g['category'])?></span><h3><?=e($displayGameTitle($g))?></h3><p><?=e($g['intro'])?></p><?php if($done):?><div class="game-completed-badge">✓ Completado · mejor <?=number_format((float)$done['best_score'],0)?>%</div><?php elseif($locked):?><div class="game-locked-badge">🔒 Completa el reto anterior para desbloquearlo</div><?php endif;?><div class="game-card-foot"><span><?=$done?'Ver resultado':($locked?'Bloqueado':'Jugar ahora')?></span><b><?=$locked?'🔒':'→'?></b></div><?php if($locked):?></article><?php else:?></a><?php endif;?><?php endforeach;?></section>
<?php else:?>
<section class="play-shell" data-game-root><div class="play-top"><div class="play-location"><div class="play-mobile-nav"><a href="./" class="back-link">← Mis juegos</a><a href="../" class="back-link play-home-link">⌂ Inicio</a><a href="?change=1" class="back-link play-exit-link" data-game-change-participant>↻ Salir</a></div><span class="play-portal-label">JUEGOS</span><strong><?=e($gameExperienceTitle)?></strong></div><div class="play-player"><span><?=e(user_initials((string)$player['name']))?></span><div><strong><?=e($player['name'])?></strong><small>Gafete <?=e($player['badge'])?></small></div></div><div class="play-progress-copy"><span data-progress-label>Preparando reto</span><strong data-score>0 pts</strong><small class="game-total-timer hidden" data-game-total-timer></small></div></div><div class="progress-track"><i data-progress-bar></i></div><section class="play-stage"><div class="game-welcome" data-welcome><div class="welcome-visual"><img src="<?=e($gameVisual)?>" alt="Ilustración de <?=e($activeGameTitle)?>"><button type="button" class="welcome-zoom-btn" data-visual-zoom>🔍 Ver imagen grande</button></div><span class="stage-icon">🎮</span><span class="eyebrow"><?=e($game['category'])?> · <?=e($game['difficulty'])?></span><h1><?=e($activeGameTitle)?></h1><p>¡Vamos, <?=e($firstName)?>! <?=e($game['intro'])?></p><div class="player-ready"><span class="player-avatar large"><?=e(user_initials((string)$player['name']))?></span><div><strong><?=e($player['name'])?></strong><small>Tu partida se registrará con el gafete <?=e($player['badge'])?>.</small></div></div><?php if($reviewMode):?><div class="review-lock-note">✓ Este juego ya fue completado. Puedes revisar tu resultado, pero no volver a enviarlo.</div><?php else:?><button class="start-personalized-game" type="button" data-start-game>Comenzar reto →</button><?php endif;?></div><div class="challenge hidden" data-challenge></div><div class="game-finish hidden" data-finish></div></section></section>
<?php endif;?></main><footer class="games-footer"><?=e($company)?> · <?=date('Y')?> · Experiencia interactiva</footer><script src="../assets/vendor/sweetalert2/sweetalert2.local.js?v=7"></script><script src="../assets/js/notify.js?v=7"></script><script src="../assets/js/fullscreen.js?v=1"></script><script src="../assets/js/games.js?v=15"></script><?php if(isset($_GET['locked'])):?><script>setTimeout(()=>showNotify('info','Este reto todavía está bloqueado. Completa primero el reto disponible.'),120);</script><?php endif;?></body></html>
